### ISSUE TITLE
Minecraft Towns and Kingdom problem with Immersive Engineering.

### ISSUE THREAD

**Issue by LuckHead** [Mikaaah/TownsAndKingdoms#79] opened 2023-05-12 12:41 UTC
When a Engineer´s Blueprint is inside a Engineer´s Workbench and i right click on the Blueprint the game crashes.

**Comment by sebkuip** [comment] 2023-05-12 12:43
Duplicate of #65

**Closed** 2023-05-23 13:11 UTC
Labels: Duplicate
